site_name: Yeti Doc
site_url: http://0.0.0.0:8888
theme:
  name: material
  logo: ./assets/YETI/yeti_white_icon.png
  favicon: ./assets/YETI/favicon.ico
  palette:
    scheme: slate
    primary: blue 

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
